# Generated by Django 4.2.7 on 2024-01-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='base',
            field=models.CharField(),
        ),
    ]
